added automatic version tagging

diff --git a/.github/workflows/publish-to-pypi.yml b/.github/workflows/publish-to-pypi.yml
--- a/.github/workflows/publish-to-pypi.yml
+++ b/.github/workflows/publish-to-pypi.yml
@@ -14,7 +14,7 @@ jobs:
     steps:
     - name: Check out code
       uses: actions/checkout@v2
-          
+
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
@@ -23,10 +23,19 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install build
+        pip install poetry toml
+
+    - name: Validate version and tag
+      run: |
+        TAG_NAME=${GITHUB_REF/refs\/tags\//}
+        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
+        if [ "v$VERSION" != "$TAG_NAME" ]; then
+          echo "Error: Tag name ($TAG_NAME) does not match version (v$VERSION)"
+          exit 1
+        fi
 
     - name: Build package
-      run: python -m build
+      run: poetry build
 
     - name: Publish to TestPyPI
       if: github.ref != 'refs/heads/main'
